### PR TITLE
change test to make it fail

### PR DESCRIPTION
**Pull request by lldelisle**

### CODE REVIEW

**Comment by lldelisle** [comment]
https://github.com/mvdbeek/iwc/actions/runs/6943613802/job/18890925721#step:11:22

**Comment by lldelisle** [comment]
At least it got the PR number:
https://github.com/mvdbeek/iwc/actions/runs/6943613802/job/18890925721#step:11:3

**Comment by lldelisle** [comment]
I think you need to change:
https://github.com/mvdbeek/iwc/blob/c7f422f051a0d167055cda4bb76fb59304cb29e2/.github/workflows/workflow_test.yml#L116
to
`issue-number: ${{ github.event.number || steps.findPr.outputs.pr }}`

**Comment by lldelisle** [comment]
I guess you just forgot to set a PAT token on your repo.

**Comment by mvdbeek** [comment]
No, it is set, and it should be active too.

**Comment by mvdbeek** [comment]
Ah, I think this might not work at all ... secrets are not available to outside forks, and GITHUB_TOKEN does not have the necessary permissions to comment, see https://docs.github.com/en/actions/security-guides/using-secrets-in-github-actions#using-secrets-in-a-workflow

**Comment by mvdbeek** [comment]
hmm, unfortunate, but I don't think we can do much here without a full-blown github app

**Comment by lldelisle** [comment]
:disappointed:

**Comment by lldelisle** [comment]
~Do you think we can set a different GITHUB_USER to deploy and to comment?
For me it makes more sense that the GITHUB_USER which comments is `galaxyproject` (I don't know if it is possible) this way it will write comments to its own repo, no?~ 
Sorry does not make sense, I think the GITHUB_USER is only used for deployment. Whose PAT is it? Does he have access to your fork?

**Comment by mvdbeek** [comment]
It's my PAT and it works when I create a PR. The problem is that forks do not receive a GITHUB_TOKEN with `PullRequests: write permissions`, you can see this if you click on the `jobs`

Screenshot 2023-11-22 at 09 13 57

And secrets are not available for PRs from forks, so there's nothing left we can do.

**Comment by lldelisle** [comment]
Sorry to insist but this is super frustrating...
Do you think the `pull_request_target` is the solution?
https://github.blog/2020-08-03-github-actions-improvements-for-fork-and-pull-request-workflows/#improvements-for-public-repository-forks

**Comment by mvdbeek** [comment]
Isn't this for private repositories only ? And if that works we've got to be very, very careful since PRs can then be used to get the PAT.

**Comment by lldelisle** [comment]
I think I found what we need to do:
https://securitylab.github.com/research/github-actions-preventing-pwn-requests/
Create a new workflow:
```yml
name: Comment on the pull request

# read-write repo token
# access to secrets
on:
  workflow_run:
    workflows: ["Galaxy Workflow Tests for push and PR"]
    types:
      - completed

jobs:
  upload:
    runs-on: ubuntu-latest
    if: >
      github.event.workflow_run.event == 'pull_request' &&
      github.event.workflow_run.conclusion == 'failure'
    steps:
      - name: 'Download artifact'
        uses: actions/github-script@v3.1.0
        with:
          script: |
            var artifacts = await github.actions.listWorkflowRunArtifacts({
               owner: context.repo.owner,
               repo: context.repo.repo,
               run_id: ${{github.event.workflow_run.id }},
            });
            var matchArtifact = artifacts.data.artifacts.filter((artifact) => {
              return artifact.name == "'All tool test results'"
            })[0];
            var download = await github.actions.downloadArtifact({
               owner: context.repo.owner,
               repo: context.repo.repo,
               artifact_id: matchArtifact.id,
               archive_format: 'zip',
            });
            var fs = require('fs');
            fs.writeFileSync('${{github.workspace}}/pr.zip', Buffer.from(download.data));
      - run: unzip pr.zip

      - name: 'Comment on PR'
        uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            var fs = require('fs');
            var issue_number = Number(fs.readFileSync('./NR'));
            await github.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issue_number,
              body: fs.readFileSync('./tool_test_output.md')
            });

```

And modify the existing workflow to get the PR number:
```yml

      - name: Save PR number
        run: |
          echo ${{ github.event.number }} > ./upload/NR
```

**Comment by lldelisle** [comment]
If you think it can work, I implement it into my fork and then you make me a PR with a test failing.

**Pull request closed without merging**
